### ISSUE TITLE
failing to login

### ISSUE THREAD

**Issue by Seme4eg** [zevlg/telega.el#337]
## Telega Setup
*OS*: 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux
*Emacs*: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-26 (doom emacs)
*Telega*: telega v0.7.100 (TDLib v1.7.10) (telega-server v0.7.13)

Installation method MELPA

## Current Behavior
installed all prerequisites for tdlib, cloned it, copiled it, installed it, everything like in docs, no errors. Added (package! telega) to my doom config (it just installs 'telega' using 'straight' under the hood), didn't customise anything, tried to login, got prompted for a phone, entered it, entered the code and got the error output below (1st image). Then after i close this error i am getting another status-related error each second (2nd image) and in order to stop getting these i need to run `telega-logout`. What's interesting - that it loads my groups and then errors appear (3nd image)

![image](https://user-images.githubusercontent.com/24554850/146753283-f2e85c7e-217a-43ee-b637-dcaf498f420a.png)
![image](https://user-images.githubusercontent.com/24554850/146753466-1577fd7b-7892-4a57-b85e-c89919aecf0f.png)
![image](https://user-images.githubusercontent.com/24554850/146754369-5a8ac8c9-ae77-4ba1-8e8a-7cc00b418b27.png)

**Comment by zevlg** [comment]
Fixed in the master, please check it out

**Comment by Seme4eg** [comment]
It doesn't throw an error now every second now, but i still get an error after entering login code

![image](https://user-images.githubusercontent.com/24554850/146827155-033f6342-e636-4ccc-adfd-7962f821c97f.png)

**Comment by Seme4eg** [comment]
Everything works now, thank you!
